In [1]:
import numpy as np

In [130]:
class LinearSystem:
    
    def __init__(self, M,b):
        
        self.M = M
        self.b = b
        
    def JacobiMethod(self, itmax=1000, error=1e-10):
        
        rows,col = M.shape
        it = 0
        
        sol = np.zeros(col)
        
        sumatoria = np.zeros_like(sol)
        
        res = np.linalg.norm(b - np.dot(M,sol))
        
        while res > error and it < itmax:
            
            for i in range(rows):
                
                sum_ = 0
                
                for j in range(col):
                    
                    if i != j:
                        sum_ += M[i][j]*sol[j]
                        
                sumatoria[i] = sum_
                
            for k in range(rows):
                
                if M[k][k] != 0:
                    
                    sol[k] = (b[k] - sumatoria[k])/M[k][k]
                    
                else:
                    print('No se puede solucionar con el método de Jacobi')
                    
            res = np.linalg.norm( b - np.dot(M,sol) )
            
            it += 1
        
        print('Iteraciones realizadas:', str(it))
        
        return sol
    
    
    def GaussSeidelMethod(self, itmax=1000, error=1e-10):
        
        rows,col = M.shape
        it = 0
        
        sol = np.zeros(col)
        
        res = np.linalg.norm(b - np.dot(M,sol))
        
        while res > error and it < itmax:
            
            for i in range(rows):
                
                sum_ = 0
                
                for j in range(col):
                    
                    if i != j:
                        sum_ += M[i][j]*sol[j]
                        
                sol[i] = (b[i] - sum_)/M[i][i] 
                
              
            res = np.linalg.norm( b - np.dot(M,sol) )
            
            it += 1
        
        print('Iteraciones realizadas:', str(it))
        
        return sol

# Método de Jacobi

In [136]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [137]:
syst1 = LinearSystem(M,b)

In [138]:
syst1.JacobiMethod()

Iteraciones realizadas: 23


array([1., 1., 1.])

# Método de Gauss-Seidel (Punto 1)

In [139]:
syst2 = LinearSystem(M,b)

In [140]:
syst2.GaussSeidelMethod()

Iteraciones realizadas: 18


array([1., 1., 1.])