In [1]:
import numpy as np

$$AB = \begin{pmatrix}
1 & 0 & 0 \\ 
5 & 1 & 0 \\
-2 & 3 & 1 \\
\end{pmatrix}
\begin{pmatrix}
4 & -2 & 1\\ 
0 & 3 & 7\\ 
0&0&2\\ 
\end{pmatrix}
=\begin{pmatrix}
4&-2&1\\
20&-7&12\\
-8&13&21\\
\end{pmatrix}$$

In [22]:
def GetMatrixMultiplication(M1,M2):
    
    colM1 = len(M1[0])
    rowsM1 = len(M1)
    colM2 = len(M2[0])
    rowsM2 = len(M2)
    
    if colM1 != rowsM2:
        print('No se pueden multiplicar')
        return None
    
    sol = np.zeros((rowsM1,colM2))
    
    for i in range(rowsM1):      
        
        for j in range(colM2):
            
            sum_ = 0
            for a in range(rowsM1):
                
                sum_ += M1[i][a]*M2[a][j]
                
            sol[i][j] = sum_
            
    return sol

In [35]:
M1 = np.array(([1,0,0],[5,1,0],[-2,3,1]))
M2 = np.array(([4,-2,1],[0,3,7],[0,0,2]))

print(M1)
print(M2)

[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
[[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]


In [36]:
sol = GetMatrixMultiplication(M1,M2)

print(sol)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
