In [3]:
import numpy as np

In [131]:
b = np.array([-3,-3,8,9])
A = np.array([[3,1,-1],[1,2,0],[0,1,2],[1,1,-1]]) 


M = np.array([[3,1,0,1],[1,2,1,1],[-1,0,2,-1]])
print(M)

[[ 3  1  0  1]
 [ 1  2  1  1]
 [-1  0  2 -1]]


# Mínimos Cuadrados

In [133]:

def GetFit(x,y):
 
    b = y

    AT = np.dot(x.T,x)
    bT = x.T @ b

    xsol = np.linalg.solve(AT,bT)
    
    return xsol


In [134]:
z=GetFit(A,b)
z

array([-1.,  2.,  1.])

In [135]:
projection = np.dot(A,z)
print(projection)
print(np.round(projection))

[-2.00000000e+00  3.00000000e+00  4.00000000e+00  1.11022302e-16]
[-2.  3.  4.  0.]


# Gram-Schmidt

In [136]:

def GramSchmidt(V):
    
    Base = np.zeros((V.shape[0],V.shape[1]))
    
    Base[0] = V[0]
    
    vectors = 0
    
    for i in range(len(V)):
        Base[i] = V[i]
        
        for j in range(i):
            Base[i] = Base[i] - (np.dot(V[i],Base[j]))/(np.dot(Base[j],Base[j]))*Base[j]
            
    for k in range(len(Base)):
        Norm = np.linalg.norm(Base[k])
        Base[k] = Base[k]/Norm
    
    return Base
        

In [137]:
Base = GramSchmidt(M)

In [138]:
Proy = (np.dot(b,Base[0]))*Base[0] + (np.dot(b,Base[1]))*Base[1] + (np.dot(b,Base[2]))*Base[2]
print(Proy)

[-2.  3.  4.  0.]
